### ISSUE TITLE
privacy param doesn't work

### ISSUE THREAD

**Issue by imakihi** [CartoDB/carto-python#15]
Hi there. Great work on this library. 
I wanted to use privacy param in my code like following

fi = FileImport(import_file, cl, {"privacy":"public"})

but I could not make it work. I talked to Javier and he said this parm is not supported. Is this true? Is there anyway to include this param to the library?

Thank you for you nice work!

Hiroo

**Comment by alrocar** [comment]
Hi Hiroo,

we are working on the next carto-python 1.0.0 release.

This is already fixed in branch _1.0.0-namedmaps_. carto-python APIs have changed and they will be properly documented, meanwhile you can find an example for creating a public dataset in `test_create_and_modify_and_delete_dataset_from_file` inside the `test_datasets.py`
