### ISSUE TITLE
attribute dependent_visualizations only returns one visualization

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/carto-python#161]
* Python SDK version: `carto==1.8.4`

I'm trying to get all visualizations associated to a single dataset that has 11 visualizations associated to it. However, when I'm using the DatasetManager class I'm only able to get the first visualization:

```python
# Authenticate to CARTO account
auth_client = APIKeyAuthClient(CARTO_BASE_URL, CARTO_API_KEY, 'organization')

dataset_manager = DatasetManager(auth_client)

dataset = dataset_manager.get('tableName')

associated_maps = [map.name for map in dataset.dependent_visualizations]

print(associated_maps)
```

Is this behaviour expected? cc @alrocar

**Comment by alrocar** [comment]
Yes, dependent visualizations [is not fully supported](https://github.com/CartoDB/carto-python/blob/master/carto/datasets.py#L135), it was added to avoid deleting a dataset that had dependent maps. We don't want to fully support it by default since retrieving dependent vizs is expensive.

I can only suggest you to:

- A workaround, by calling the viz API for the whole list of dependent_visualizations
- Optionally wrap it in a method `dataset.get_dependent_visualizations` so everyone could benefit of that feature

**Comment by oriolbx** [comment]
The problem that I see with the viz API option is that, as far as I know is not a public API. 

In any case, we can close this issue then. Thanks! :)
