### ISSUE TITLE
Extend the status check to the data_manager

### ISSUE THREAD

**Issue by jsanz** [CartoDB/carto-python#61]
At this moment one can only check the status of an import on the Sync Manager, which is strange because it should be possible to check the status of any import, both from local and remote resources. I mean once a local resource has been uploaded it should return the control and with the import identifier to be able to check the status for the rest of the process happening at the CARTO instance.

**Comment by alrocar** [comment]
OK, I think this is a bit confusing but the `DatasetManager` is conceptually different from both `SyncTableJobManager` and `FileImportJobManager`.

The `DatasetManager` creates the jobs and deals with their `state` to return a `Dataset` instance or a `CartoException`. See [this](https://github.com/CartoDB/carto-python/blob/master/carto/datasets.py#L185-L207).

On the other hand, `SyncTableJobManager` and `FileImportJobManager` expose the `state` attribute because they return a `job` that you have to check its `state` to know when it finished/succeed/etc.

Maybe we should simply state this clearly on the docs?

**Comment by alrocar** [comment]
Added proper documentation to explain the difference between DatasetManager and JobManagers. 

Closing the issue.
